[book]
title = "The Rust Performance Book 中文翻译"
authors = ["Nicholas Nethercote", "Fleeting Lore"]
src = "src"
language = "zh"

[build]
create-missing = false

[rust]
edition = "2024"

[output.html]
smart-punctuation = true
default-theme = "ayu"
git-repository-url = "https://github.com/FleetingLore/perf-book-zh"
edit-url-template = "https://github.com/nnethercote/perf-book/edit/master/{path}"
site-url = "https://nnethercote.github.io/perf-book/"
